version: '3'
services:
  dev:
    image: ${NAME}
    hostname: devcon
    privileged: true
    command: /entrypoint.sh ${USER}
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    volumes:
      - devcon_ksaito:/home/${USER}:cached
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  devcon_ksaito:
